# Generated by Django 4.2 on 2023-06-30 10:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='LipaNaMpesa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('short_code', models.PositiveIntegerField()),
                ('reference', models.CharField(max_length=100)),
            ],
        ),
    ]
