# Generated by Django 4.1.6 on 2023-03-10 00:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0002_alter_client_profile_pic"),
    ]

    operations = [
        migrations.AlterField(
            model_name="client",
            name="profile_pic",
            field=models.ImageField(
                blank=True,
                default="/static/images/profile1.png",
                null=True,
                upload_to="",
            ),
        ),
    ]
