# Generated by Django 4.1.6 on 2023-03-12 15:18

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("app", "0004_alter_client_profile_pic"),
    ]

    operations = [
        migrations.CreateModel(
            name="Shop",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("food", "food"),
                            ("clothing", "clothing"),
                            ("electronics", "electronics"),
                            ("vehicles", "vehicles"),
                            ("cyber", "cyber"),
                            ("supermarket", "supermarket"),
                            ("fruits_vegetables", "fruits_vegetables"),
                            ("hardware", "hardware"),
                        ],
                        max_length=20,
                    ),
                ),
                ("location", models.CharField(max_length=30)),
                ("image", models.ImageField(upload_to="media/")),
                (
                    "owner",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Product",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("item_name", models.CharField(max_length=100)),
                ("image", models.ImageField(upload_to="media/")),
                (
                    "delivery",
                    models.CharField(
                        choices=[
                            ("free delivery", "free delivery"),
                            ("no delivery", "no delivery"),
                        ],
                        max_length=15,
                    ),
                ),
                ("instock", models.PositiveIntegerField()),
                ("new_price", models.PositiveIntegerField()),
                ("old_price", models.PositiveIntegerField()),
                ("description", models.TextField(max_length=200)),
                (
                    "item_owner",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "item_shop",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="app.shop"
                    ),
                ),
            ],
        ),
    ]
