# Generated by Django 4.1.6 on 2023-03-13 11:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0005_shop_product"),
    ]

    operations = [
        migrations.RenameField(
            model_name="product",
            old_name="item_name",
            new_name="product_name",
        ),
        migrations.RenameField(
            model_name="product",
            old_name="item_owner",
            new_name="product_owner",
        ),
        migrations.RenameField(
            model_name="product",
            old_name="item_shop",
            new_name="product_shop",
        ),
        migrations.AlterField(
            model_name="shop",
            name="category",
            field=models.CharField(
                choices=[
                    ("fashion", "fashion"),
                    ("jewellery", "jewellery"),
                    ("electronics", "electronics"),
                    ("automotive", "automotive"),
                    ("cyber", "cyber"),
                    ("elicasies", "delicasies"),
                    ("grocery", "grocery"),
                    ("retail", "retail"),
                ],
                max_length=20,
            ),
        ),
    ]
