# Generated by Django 4.1.6 on 2023-03-14 17:32

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("app", "0008_alter_product_product_owner_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="product",
            name="product_owner",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL
            ),
        ),
        migrations.AlterField(
            model_name="product",
            name="product_shop",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="app.shop"
            ),
        ),
        migrations.AlterField(
            model_name="shop",
            name="owner",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL
            ),
        ),
    ]
